print("Please enter the test to change")
name=input()
print("enter text to replace \n")
text=input()
print("enter the text replaced by \n")
to_text=input()
name=name.replace(text, to_text)
print(name)